import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#f6f3ee',
        background: '#fcf9f4',
        'inverse-primary': '#c8c6c5',
        'on-primary-fixed-variant': '#474746',
        'surface-container-highest': '#e5e2dd',
        'on-secondary-fixed-variant': '#862201',
        'tertiary-fixed': '#8cf5e4',
        'on-secondary': '#ffffff',
        'secondary-fixed': '#ffdbd1',
        'on-error-container': '#93000a',
        primary: '#000000',
        'tertiary-container': '#00201c',
        'on-primary-container': '#858383',
        'on-primary': '#ffffff',
        'primary-fixed': '#e5e2e1',
        'inverse-surface': '#31302d',
        'secondary-container': '#fe7952',
        'on-background': '#1c1c19',
        'on-surface-variant': '#444748',
        'tertiary-fixed-dim': '#6fd8c8',
        'primary-container': '#1c1b1b',
        'surface-container-high': '#ebe8e3',
        outline: '#747878',
        'on-secondary-fixed': '#3b0900',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#6c1900',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        tertiary: '#000000',
        secondary: '#a73918',
        'inverse-on-surface': '#f3f0eb',
        'on-surface': '#1c1c19',
        'surface-container': '#f0ede8',
        'outline-variant': '#c4c7c7',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed': '#1c1b1b',
        surface: '#fcf9f4',
        'surface-dim': '#dcdad5',
        error: '#ba1a1a',
        'on-tertiary-fixed': '#00201c',
        'on-tertiary-fixed-variant': '#005048',
        'surface-bright': '#fcf9f4',
        'surface-tint': '#5f5e5e',
        'secondary-fixed-dim': '#ffb5a0',
        'surface-variant': '#e5e2dd',
        'on-tertiary-container': '#1a9486',
        'primary-fixed-dim': '#c8c6c5',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '64px',
        gutter: '24px',
        unit: '8px',
        'container-max': '1200px',
        'margin-mobile': '24px',
      },
      // Mapped to your uploaded fonts via CSS variables (see lib/fonts.ts)
      fontFamily: {
        'body-md': ['var(--font-plain-black-wide)'],
        'label-lg': ['var(--font-jim-nightshade)'],
        'headline-sm': ['var(--font-blacksword)'],
        'display-lg': ['var(--font-blacksword)'],
        'body-lg': ['var(--font-plain-black-wide)'],
        'label-sm': ['var(--font-jim-nightshade)'],
        'headline-md': ['var(--font-blacksword)'],
        'headline-lg': ['var(--font-blacksword)'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '56px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

export default config;
