import { portableTextToPlainText } from './portableText';
import { resolveImageSrc } from './sanity.image';
// Generated by scripts/generate-logo-meta.mjs (runs pre-dev/pre-build) --
// NOT read via fs at runtime. A runtime fs.readFileSync from public/ works
// locally and at build time but throws ENOENT in Vercel's serverless
// functions, since Next's static import tracing can't see a dynamically
// constructed fs path and so never bundles the file into /var/task. See
// the /studio 500 postmortem. Import the pre-computed constant instead.
import { LOGO_PATH, LOGO_WIDTH, LOGO_HEIGHT } from './generated/logo-meta';

export const SITE_URL = 'https://cloveandcauldron.co';
export const SITE_NAME = 'Clove & Cauldron';

// Raster (PNG) version of the icon mark, for Google's Organization logo
// rich-result eligibility -- Google doesn't accept SVG for that.
const LOGO_URL = `${SITE_URL}${LOGO_PATH}`;

// Google's Organization logo rich result wants a roughly square image
// (and at least 112x112px) -- this check exists so a future logo swap
// can't silently regress into an elongated mark that won't qualify.
const LOGO_ASPECT_RATIO = LOGO_WIDTH / LOGO_HEIGHT;
if (LOGO_WIDTH < 112 || LOGO_HEIGHT < 112 || LOGO_ASPECT_RATIO > 1.25 || LOGO_ASPECT_RATIO < 0.8) {
  console.warn(
    `[seo] JSON-LD logo ${LOGO_PATH} is ${LOGO_WIDTH}x${LOGO_HEIGHT} (ratio ${LOGO_ASPECT_RATIO.toFixed(2)}) -- does not meet Google's "roughly square, min 112x112" guidance for the Organization logo rich result. A square icon-style crop would be needed for that rich result specifically; the JSON-LD itself remains valid regardless.`
  );
}

// Trims plain text to a meta-description-friendly length without cutting
// mid-word, since search engines truncate awkwardly otherwise.
export function truncate(text: string, maxLength: number): string {
  const trimmed = text.trim().replace(/\s+/g, ' ');
  if (trimmed.length <= maxLength) return trimmed;

  const cut = trimmed.slice(0, maxLength);
  const lastSpace = cut.lastIndexOf(' ');
  return `${cut.slice(0, lastSpace > 0 ? lastSpace : maxLength)}…`;
}

// Shared by generateMetadata and the Article JSON-LD block so both read the
// same title/description/image, rather than re-deriving the fallback chain
// (metaTitle/metaDescription overrides -> dek -> body excerpt) in two places.
export function getArticleSeo(article: any) {
  const title = article.metaTitle || article.title;
  const description =
    article.metaDescription ||
    article.dek ||
    truncate(portableTextToPlainText(article.body), 155);
  const imageSource = article.ogImage || article.coverImage;
  const image = resolveImageSrc(imageSource, 1200, 630);
  const imageAlt = imageSource?.alt || title;
  return { title, description, image, imageAlt };
}

// `dangerouslySetInnerHTML`-safe JSON-LD serialization: escapes `<` so a
// body value containing "</script>" can't break out of the script tag.
export function serializeJsonLd(data: unknown): string {
  return JSON.stringify(data).replace(/</g, '\\u003c');
}

export function buildArticleJsonLd(article: any, slug: string) {
  const { title, description, image } = getArticleSeo(article);
  const url = `${SITE_URL}/articles/${slug}`;
  // No author field exists on the article schema -- every piece is written
  // in-house, so the Organization itself is the byline.
  const author = { '@type': 'Organization', name: SITE_NAME, url: SITE_URL };

  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: title,
    description,
    image: [image],
    // Body copy quotes a lot of Turkish/Arabic terms -- pin the primary
    // content language explicitly so crawlers don't have to guess.
    inLanguage: 'en',
    datePublished: article.publishedAt,
    dateModified: article._updatedAt || article.publishedAt,
    author,
    publisher: {
      '@type': 'Organization',
      name: SITE_NAME,
      logo: {
        '@type': 'ImageObject',
        url: LOGO_URL,
        width: LOGO_WIDTH,
        height: LOGO_HEIGHT,
      },
    },
    mainEntityOfPage: { '@type': 'WebPage', '@id': url },
  };
}

export function buildSiteJsonLd() {
  const sameAs = [
    'https://instagram.com/cloveandcauldron',
    'https://youtube.com/@cloveandcauldron',
    'https://tiktok.com/@cloveandcauldron',
  ];

  const website = {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: SITE_NAME,
    url: SITE_URL,
  };

  const organization = {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: SITE_NAME,
    url: SITE_URL,
    logo: LOGO_URL,
    sameAs,
  };

  return { website, organization };
}
